### ISSUE TITLE
Does beego support hot reload conf?

### ISSUE THREAD

**Issue by Zhang21** [beego/beego#5294]
Basic infos:

```yml
beego: v1.12.3
go: v1.16
os: linux
arch: amd64
```

<br/>

Does beego support hot reload conf after modify the `app.conf` file?

Like prometheus:

```sh
curl -X POST http://prometheus:9090/-/reload
```
